# Generated by Django 6.0.7 on 2026-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_emailqueue_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Drafts stay in the outbox untouched until they are explicitly sent.'),
        ),
    ]
